# Generated by Django 3.0.5 on 2020-05-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudentsapp', '0002_auto_20200511_0826'),
        ('acountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(related_name='users', to='groupstudentsapp.GroupOfStudents', verbose_name='группа'),
        ),
    ]
