# Generated by Django 3.0.5 on 2020-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudentsapp', '0003_auto_20200511_0827'),
        ('acountapp', '0003_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='users', to='groupstudentsapp.GroupOfStudents', verbose_name='группа'),
        ),
    ]
