# Generated by Django 3.0.5 on 2020-05-11 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupstudentsapp', '0003_auto_20200511_0827'),
        ('acountapp', '0004_auto_20200511_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='позиция')),
                ('is_teacher', models.BooleanField(verbose_name='статус преподавателя')),
                ('foto', models.ImageField(blank=True, upload_to='user_avatar', verbose_name='фото')),
                ('group', models.ManyToManyField(blank=True, related_name='users', to='groupstudentsapp.GroupOfStudents', verbose_name='группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
