# Generated by Django 3.0.5 on 2020-05-11 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudentsapp', '0003_auto_20200511_0827'),
        ('courseapp', '0002_auto_20200511_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lesson', to='groupstudentsapp.GroupOfStudents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 10, 25, 45, 375062, tzinfo=utc), verbose_name='окончание занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson', to='courseapp.Place'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 10, 25, 45, 375043, tzinfo=utc), verbose_name='начало занятия'),
        ),
    ]
