# Generated by Django 3.0.5 on 2020-05-11 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudentsapp', '0003_auto_20200511_0827'),
        ('courseapp', '0003_auto_20200511_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 10, 53, 5, 626200, tzinfo=utc), verbose_name='окончание занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson', to='groupstudentsapp.GroupOfStudents', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 10, 53, 5, 626183, tzinfo=utc), verbose_name='начало занятия'),
        ),
    ]
