# Generated by Django 3.0.5 on 2020-05-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupofstudents',
            options={'managed': True, 'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группы студентов'},
        ),
        migrations.RemoveField(
            model_name='groupofstudents',
            name='students',
        ),
    ]
