# Generated by Django 3.0.5 on 2020-05-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupstudentsapp', '0002_auto_20200511_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupofstudents',
            options={'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группы студентов'},
        ),
    ]
